// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvztkshpltevrgcbflfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2enRrc2hwbHRldnJnY2JmbGZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NTg2NTQsImV4cCI6MjA1OTMzNDY1NH0.dWvzKXqBECV9dxQ7JPSo-OxCV06hl20dsP7h0xGMNHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);